name: CI

on: [push, pull_request]

jobs:
  ci:
    name: ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: [14, 16, 18]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install
      run: npm ci
    - name: Test
      run: npm test
